### ISSUE TITLE
stream with cancel problem?

### ISSUE THREAD

**Issue by mjibson** [psycopg/psycopg3#30]
I think the new `stream` stuff might not work correctly with `cancel`. Here's some example code using a version of materialize that correctly supports cancellation. I wasn't able to get a repro under postgres using `SELECT`, but I'm medium confident this is a psycopg3 stream related bug (my test using COPY with cancel and psycopg3 works fine).

Or I'm doing something totally wrong. Not sure.

```
import psycopg3

dsn = "postgresql://materialize@localhost:6875/materialize?sslmode=disable"

conn = psycopg3.connect(dsn)
with conn.cursor() as cur:
    conn.autocommit = True
    cur.execute("DROP TABLE IF EXISTS t")
    cur.execute("CREATE TABLE t (a int)")
    cur.execute("INSERT INTO t VALUES (1), (2)")
    conn.autocommit = True
    stream = cur.stream("TAIL t")
    print(next(stream))
    print(next(stream))
    conn.cancel()
    try:
        print(next(stream))
    except Exception as e:
        print("exception:", e)
    print("DONE")
    print(cur.execute("select 1"))
```

requirements.txt:

```
git+https://github.com/psycopg/psycopg3.git@4f053f14901454a7c7895b527ddeb9d8ab57d7fe#subdirectory=psycopg3
```

output is:

```
(Decimal('1612558651418'), 1, 1)
(Decimal('1612558651418'), 1, 2)
exception: canceling statement due to user request
DONE
Traceback (most recent call last):
  File "m.py", line 26, in <module>
    print(cur.execute("select 1"))
  File "/usr/local/lib/python3.7/site-packages/psycopg3/cursor.py", line 469, in execute
    self._conn.wait(self._execute_gen(query, params, prepare=prepare))
  File "/usr/local/lib/python3.7/site-packages/psycopg3/connection.py", line 519, in wait
    return waiting.wait(gen, self.pgconn.socket, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/psycopg3/waiting.py", line 223, in wait_epoll
    s = next(gen)
  File "/usr/local/lib/python3.7/site-packages/psycopg3/cursor.py", line 192, in _execute_gen
    yield from self._maybe_prepare_gen(pgq, prepare)
  File "/usr/local/lib/python3.7/site-packages/psycopg3/cursor.py", line 224, in _maybe_prepare_gen
    self._execute_send(pgq)
  File "/usr/local/lib/python3.7/site-packages/psycopg3/cursor.py", line 332, in _execute_send
    self._conn.pgconn.send_query(query.query)
  File "/usr/local/lib/python3.7/site-packages/psycopg3/pq/pq_ctypes.py", line 242, in send_query
    raise PQerror(f"sending query failed: {error_message(self)}")
psycopg3.pq.PQerror: sending query failed: another command is already in progress
```

**Comment by dvarrazzo** [comment]
Hello Matt,

I know little about how the stream works, you probably know the insides better than me. However looking at CockroachDB's [CHANGEFEED](https://www.cockroachlabs.com/docs/stable/changefeed-for.html) it seems that the only way to have a correct shutdown is to have the stream interrupted by the server, otherwise the protocol remains in an intermediate state which cannot be recovered if not closing the connection. Probably resetting the connection would work too: would you like to try? There isn't a `reset()` yet on the `Connection` object but you can try to use the libpq call exposed as `conn.pgconn.reset()`

Does Materialise have a way to terminate the TAIL operation server-side?

**Comment by dvarrazzo** [comment]
Assuming this ticket can be closed
